### PR TITLE
Adding tests for new functionality

### PR DESCRIPTION
**Pull request by nkorinek**
Added tests to test clipping by a multipolygon and clipping a mixed geodataframe.

### CODE REVIEW

**Comment by nkorinek** [comment]
@lwasser

**Comment by nkorinek** [comment]
@lwasser the changes for the vignette are in this PR, I did them on the same branch. Do you want it as a separate PR, or is this ok?

**Comment by lwasser** [comment]
@nkorinek this is ok. i am not sure how i missed this PR last week!! but i'll look at both now!! :)

**Comment by lwasser** [comment]
@nkorinek merging this to trigger ci on our end!! :)

**Pull request merged**
